name: Run E2E Test Suite 

# Controls when the workflow will run
on:
  pull_request:
  
  push:
    branches:
      - 'develop'
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
# This workflow contains a single job called "build"
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Dependencies
        run: cd example/ && npm ci
      - name: Start WordPress Instance
        run: npm run wp-env start
      - name: Run Cypress E2E Tests
        uses: cypress-io/github-action@v2.9.7
        with:
          # Sends test results to Cypress Dashboard
          record: true
          # Whether or not to load balance tests using multiple containers
          parallel: false
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }