name: Run E2E Test Suite 
on: [push, workflow_dispatch]
permissions:
  contents: read

jobs:
  cypress:
    name: Cypress
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
      - name: Run Cypress E2E Tests
        uses: cypress-io/github-action@v5
        with:
          build: npm run build-test-env
          start: npm run start-test-env
          wait-on: 'http://localhost:8888/wp-admin/index.php, http://localhost:8889'
          wait-on-timeout: 220
          browser: chrome
          record: true
          parallel: false
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
