name: Lint Pull Request
on: [push, workflow_dispatch]

jobs:
  eslint:
    name: ESLint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: reviewdog/action-eslint@v1.0.0
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          filter_mode: diff_context