name: Publish @next version to NPM
on:
  push:
    branches:
      - 'develop'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - run: npm ci
      
      - name: npm update version and release
        run: |
          npm version prerelease --preid=next
          npm publish --tag next
        env:
           NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
