name: Publish @next version to NPM
on:
  push:
    branches:
      - 'develop'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
      - run: npm ci
      - env:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - run: npm version prerelease --preid=next && npm publish --tag next