name: Publish @next version to NPM
on:
  pull_request:
    branches:
      - 'develop'
    types: [closed]
jobs:
  build:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
      - run: npm ci
      
      - name: Configure git user name and email
        run: |
            git config user.name "10up Bot"
            git config user.email "pr@10up.com"

      - name: npm update version and release
        run: |
          npm version prerelease --preid=next
          npm publish --tag next
        env:
           NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
