name: Run Unit Test Suite 

# Controls when the workflow will run
on:
  pull_request:
  
  push:
    branches:
      - 'develop'
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
# This workflow contains a single job called "build"
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install NPM Dependencies
        run: npm ci
      - name: Run Unit Tests
        run: npm test
